### ISSUE TITLE
Invalid HTML error if the content contains special characters (<3)

### ISSUE THREAD

**Issue by mrdeeds88** [arendjr/text-clipper#24] opened 2023-12-22 08:26 UTC
Hi there,
I tested with the content that contains the heart icon using "<3"
It shows error:
`text-clipper.js?v=44260d94:173 Uncaught Error: Invalid HTML: the text <3 <3`

![0h9zieA](https://github.com/arendjr/text-clipper/assets/2483279/27edda2f-7ac3-4b13-bcf8-04a73b301493)

Do you have any idea for fixing this?

Thanks!

**Comment by mrdeeds88** [comment] 2023-12-22 08:39
I was fixed this by pre-format the content before parse it to clipper.

**Comment by arendjr** [comment] 2023-12-22 09:08
Yeah, I would say this is by design, since "<3" should be encoded as `&lt;3` to be valid HTML. I suppose things could be made a bit more resilient by implementing the fallbacks that HTML5 specifies for *invalid* HTML, but I'm afraid that would add a huge amount of complexity to the library.

So I'm closing since you found a workaround. Thanks for the report, it's indeed something to be aware of!

**Closed as completed by arendjr** 2023-12-22 09:08 UTC
